services:
  spark:
    image: docker.io/bitnami/spark:3.5
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
      - SPARK_DIST_CLASSPATH=$(hadoop classpath)
    volumes:
      - ./hadoop-config:/opt/hadoop/etc/hadoop
    ports:
      - '8080:8080'
      - '7077:7077'
    depends_on:
      - hadoop-namenode
      - hadoop-datanode

  spark-worker:
    image: docker.io/bitnami/spark:3.5
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
      - SPARK_DIST_CLASSPATH=$(hadoop classpath)
    volumes:
      - ./hadoop-config:/opt/hadoop/etc/hadoop
    depends_on:
      - spark
      - hadoop-namenode
      - hadoop-datanode

  hadoop-namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    environment:
      - CLUSTER_NAME=test
    ports:
      - "9870:9870"
    volumes:
      - hadoop_namenode:/hadoop/dfs/name

  hadoop-datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://hadoop-namenode:9000
    ports:
      - "9864:9864"
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    depends_on:
      - hadoop-namenode

  # etl:
  #   image: ghcr.io/umbertocicciaa/airflightsbe:latest
  #   ports:
  #     - '5001:5000'
  #   depends_on:
  #     - spark
  #     - spark-worker
  #   volumes:
  #     - ./shared-filesystem:/mnt/shared-filesystem:rw

  frontend:
    image: ghcr.io/umbertocicciaa/airflightsfe:latest
    depends_on:
      # - etl
      - redis
      - script
      - spark
      - spark-worker
    volumes:
      - ./shared-filesystem:/mnt/shared-filesystem:rw
    ports:
      - '8501:8501'

  script:
    image: airflightsscript:v1
    depends_on:
      - spark
      - spark-worker
    volumes:
      - ./shared-filesystem:/mnt/shared-filesystem:rw

  redis:
    image: redis
    ports:
      - '6379:6379'

volumes:
  hadoop_namenode:
  hadoop_datanode: