services:
  spark:
    image: docker.io/bitnami/spark:3.5
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    ports:
      - '8080:8080'
      - '7077:7077'

  spark-worker:
    image: docker.io/bitnami/spark:3.5
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark

  etl:
    image: ghcr.io/umbertocicciaa/airflightsbe:latest
    ports:
      - '5001:5000'
    depends_on:
      - spark
      - spark-worker
    volumes:
      - ./shared-filesystem:/mnt/shared-filesystem:rw

  frontend:
    image: ghcr.io/umbertocicciaa/airflightsfe:latest
    depends_on:
      - etl
      - redis
      - script
      - spark
      - spark-worker
    volumes:
      - ./shared-filesystem:/mnt/shared-filesystem:rw
    ports:
      - '8501:8501'


  script:
    image: ghcr.io/umbertocicciaa/airflightsscript:latest
    depends_on:
      - spark
      - spark-worker
    volumes:
      - ./shared-filesystem:/mnt/shared-filesystem:rw

  redis:
    image: redis
    ports:
      - '6379:6379'