apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 8501
    hostPort: 8501
    listenAddress: "0.0.0.0"
    protocol: tcp
- role: worker
