apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: airflights
  template:
    metadata:
      labels:
        app: airflights
    spec:
      containers:
      - name: airflights
        image: airflights:latest
        envFrom:
          - configMapRef:
              name: app-env
        ports:
          - containerPort: 8501
        volumeMounts:
          - name: shared-fs
            mountPath: /mnt/shared-filesystem
      volumes:
        - name: shared-fs
          persistentVolumeClaim:
            claimName: shared-fs-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-fs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: airflights-svc
spec:
  type: ClusterIP
  ports:
    - port: 8501
      targetPort: 8501
  selector:
    app: airflights
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: airflights-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: airflights.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: airflights-svc
            port:
              number: 8501