apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --out k8s/
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --out k8s/
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: app
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: src-dev-env
          image: ghcr.io/umbertocicciaa/airflights:latest
          name: app
          ports:
            - containerPort: 8501
              protocol: TCP
          volumeMounts:
            - mountPath: /mnt/shared-filesystem
              name: app-cm0
      restartPolicy: Always
      volumes:
        - configMap:
            name: app-cm0
          name: app-cm0
