apiVersion: v1
kind: Service
metadata:
  name: spark-master
spec:
  ports:
    - port: 7077
      name: spark
    - port: 8080
      name: webui
    - port: 6066
      name: rest
  selector:
    component: spark-master
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
spec:
  replicas: 1
  selector:
    matchLabels:
      component: spark-master
  template:
    metadata:
      labels:
        component: spark-master
    spec:
      containers:
      - name: spark-master
        image: bitnami/spark:3.5
        env:
          - name: SPARK_MODE
            value: "master"
          - name: INIT_DAEMON_STEP
            value: "setup_spark"
        ports:
          - containerPort: 7077
          - containerPort: 8080
          - containerPort: 6066
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      component: spark-worker
  template:
    metadata:
      labels:
        component: spark-worker
    spec:
      containers:
      - name: spark-worker
        image: bitnami/spark:3.5
        env:
          - name: SPARK_MODE
            value: "worker"
          - name: SPARK_MASTER
            value: "spark://spark-master:7077"
          - name: SPARK_WORKER_WEBUI_PORT
            value: "8081"
        ports:
          - containerPort: 8081