apiVersion: v1
kind: Service
metadata:
  name: namenode
spec:
  clusterIP: None           
  ports:
    - port: 9870
      name: webui
    - port: 8020
      name: rpc
    - port: 9000
      name: fs
  selector:
    component: namenode
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: namenode
spec:
  serviceName: namenode
  replicas: 1
  selector:
    matchLabels:
      component: namenode
  template:
    metadata:
      labels:
        component: namenode
    spec:
      containers:
      - name: namenode
        image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
        ports:
          - containerPort: 9870
          - containerPort: 8020
          - containerPort: 9000
        envFrom:
          - configMapRef:
              name: hadoop-env
        volumeMounts:
          - name: name-data
            mountPath: /hadoop/dfs/name
  volumeClaimTemplates:
  - metadata:
      name: name-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: datanode
spec:
  clusterIP: None
  ports:
    - port: 9864
      name: webui
  selector:
    component: datanode
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: datanode
spec:
  serviceName: datanode
  replicas: 2
  selector:
    matchLabels:
      component: datanode
  template:
    metadata:
      labels:
        component: datanode
    spec:
      containers:
      - name: datanode
        image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
        ports:
          - containerPort: 9864
        env:
          - name: SERVICE_PRECONDITION
            value: "namenode:9870"
        envFrom:
          - configMapRef:
              name: hadoop-env
        volumeMounts:
          - name: data-data
            mountPath: /hadoop/dfs/data
  volumeClaimTemplates:
  - metadata:
      name: data-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 50Gi