apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --file docker-compose-prod.yaml --out k8s/
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: namenode
  name: namenode
spec:
  ports:
    - name: "9870"
      port: 9870
      targetPort: 9870
    - name: "8020"
      port: 8020
      targetPort: 8020
    - name: "9000"
      port: 9000
      targetPort: 9000
  selector:
    io.kompose.service: namenode
