apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --file docker-compose-prod.yaml --out k8s/
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: spark-master
  name: spark-master
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: spark-master
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --file docker-compose-prod.yaml --out k8s/
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: spark-master
    spec:
      containers:
        - env:
            - name: INIT_DAEMON_STEP
              value: setup_spark
            - name: SPARK_MODE
              value: master
            - name: SPARK_MASTER_PORT
              value: "7077"
          image: docker.io/bitnami/spark:3.5
          name: spark-master
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 7077
              protocol: TCP
            - containerPort: 6066
              protocol: TCP
      restartPolicy: Always
