apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --file docker-compose-prod.yaml --out k8s/
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: spark-worker-1
  name: spark-worker-1
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: spark-worker-1
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --file docker-compose-prod.yaml --out k8s/
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: spark-worker-1
    spec:
      containers:
        - env:
            - name: SPARK_MASTER
              value: spark://spark-master:7077
            - name: SPARK_MODE
              value: worker
            - name: SPARK_WORKER_WEBUI_PORT
              value: "8081"
          image: docker.io/bitnami/spark:3.5
          name: spark-worker-1
          ports:
            - containerPort: 8081
              protocol: TCP
      restartPolicy: Always
