name: Backend

on:
  workflow_dispatch:
  push:
    paths:
      - 'src-backend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        install: true

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./src-backend
        push: true
        platforms: linux/amd64,linux/arm64
        tags: ghcr.io/${{ github.repository_owner }}/airflightsbe:latest
